### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by leandrobattochio** [QuestPDF/QuestPDF#1109]
**Describe the bug**

The library still seems to have some memory leak/high consumption. After each generation memory consumption increases and does not release. I limited container resources to use maximum 2560MB of memory. After 3 or 4 generation requests, container was killed and restarted. You can see here the memory drop (that's when container was restarted, probably by the linux kernel)

![Image](https://github.com/user-attachments/assets/201bc4d5-f714-4a26-a94c-67f0a8f51316)

If you need more information or code please let me know.

**To Reproduce**
A 1450 PDF with thousands of images, tables and charts.

**Expected behavior**
Memory to be released after each generation, or something that allows multiple recorrent generations without any problems.

**Screenshots**
Already provided portainer screenshot.

**Environment**
2025.1.1
AWS t3.medium Linux Instance

**Additional context**
Running on Docker Container

**Comment by EquineSolutions** [comment]
We have the same exact problem

**Comment by leandrobattochio** [comment]
Changing the lib would be the last resort for me, I can't afford that right now.

What can I do to try to effectively narrow this bug? I removed every charts and images from my PDF structure and it still hungers for more memory each time. I know how to take memory snapshots in Rider, would that help ?

**Comment by MarcinZiabek** [comment]
@leandrobattochio Would it be possible to share your project? I am dedicated to fixing this issue, but it proves to be difficult without the option to reproduce it.

Could you please share any details? Operating system? Size of documents? What content is included? What fonts are used? Do you observe this behavior when creating new project?

A memory snapshot may also be helpful.

If needed, please get in touch with me via contact@questpdf.com

**Comment by leandrobattochio** [comment]
> [@leandrobattochio](https://github.com/leandrobattochio) Would it be possible to share your project? I am dedicated to fixing this issue, but it proves to be difficult without the option to reproduce it.
> 
> Could you please share any details? Operating system? Size of documents? What content is included? What fonts are used? Do you observe this behavior when creating new project?
> 
> A memory snapshot may also be helpful.
> 
> If needed, please get in touch with me via [contact@questpdf.com](mailto:contact@questpdf.com)

Thanks for your reply! I just sent you an e-mail with cleaned project and some instructions.

**Comment by leandrobattochio** [comment]
@MarcinZiabek  can you just give a signal that you received the email? Is everything OK for your tests?

**Comment by FernandoBernardi** [comment]
Same here, I need to restart the docker container at least once in a month, it grows in my use case 100mb a day of ram.

My server has 128gb of ram it's not a huge problem for me, but it is a problem and if this project wants to grow, it need to fix this.

My environment:
Asp net: 9.0
QuestPdf: 2025.1.1
OS: Linux

** By the way, the time to generate a pdf is great, it has improved a lot in the latest updates.

**Comment by MarcinZiabek** [comment]
@leandrobattochio @FernandoBernardi @EquineSolutions 
Could you please share your exact Linux distribution? (best docker image name and version) 
Please also provide CPU architecture (x64 vs arm64).

@leandrobattochio Yes, I do confirm! Thank you so much. I am sure it will help me solve this issue.

**Comment by FernandoBernardi** [comment]
@MarcinZiabek 

Debian GNU/Linux 12 (bookworm) x64

**Comment by MarcinZiabek** [comment]
I have published version 2025.1.3, introducing a minor improvement in image memory management. Specifically, the library now properly increases GC memory pressure.

Could you confirm whether the 2025.1 release truly does not resolve the memory issue? The .NET garbage collector employs sophisticated algorithms, and during my extensive testing, I observed several interesting behaviors. In one case, the library freed native memory, but the GC retained it for a few minutes, presumably for potential reuse.

As mentioned earlier, I am committed to improving QuestPDF's memory usage. However, I want to ensure that the recent changes are indeed insufficient before making further adjustments.

Thank you for your collaboration and patience.

**Comment by leandrobattochio** [comment]
@MarcinZiabek 
Here is a simple stress test in Postman:

![Image](https://github.com/user-attachments/assets/5acb1caa-e885-4c3e-9c22-d005c1d3c516)

After several iterations:

![Image](https://github.com/user-attachments/assets/d12b6e69-f8ad-43a9-a17d-373c54270290)

It just generated the same report, over and over again. I don't think memory will ever drop again. I'm using 2025.1.1 version. The building process is pretty much what I sent you by e-mail. (sorry for the ugly code).

I will try with 2025.1.3 version and I'll update my post here.

**Comment by leandrobattochio** [comment]
Version 2025.1.3 completely broke all my pdf. Lot's of empty pages. Summary is broken too. The last version my PDF layout is working 100% is 2025.1.1. Starting from 2025.1.2 everything is broken so I can't really test it. =(

**Comment by leandrobattochio** [comment]
My summary component broke, so I removed it and I could generate with 2025.1.3 version. I'll work on that later.


### Version 2025.1.3

After consecutive 5 generations, final memory consumption is 1890,48MB.

Peaked at almost 2GB

![Image](https://github.com/user-attachments/assets/2f21c51f-bfe2-437d-b1d3-e5052615fce6)

Memory usage seems more consistent.

![Image](https://github.com/user-attachments/assets/28cfff80-1444-45b9-8f57-8d4e766f2413)

Second time I did 5 consecutives generations, in the end results were a little bit different (more final memory):

![Image](https://github.com/user-attachments/assets/e27b8bb0-14e5-4905-8a1f-5ee3c91ed4de)

It seems memory remained stable during all 5 generations not increasing to crazy levels.


### Version 2025.1.2 

It peaked to 3GB of ram!

![Image](https://github.com/user-attachments/assets/f2edbef3-9788-4190-87a9-283105204401)

After consecutive 5 generations, final memory consumption is 2008,31MB.


### Impressions

I would say unmanaged memory is being collected more now. 
My app has finished generating the reports for a while and memory stays there. It does not goes down. I've seen this behaviour in production where memory would just stay high for hours. Is this expected behaviour?


### Conclusion

I would say you are going in the right direction, but I'm not 100% confident it solved completely the issue.
Why generating the same report - _with the same data, just sequentially calling ```GeneratePdf()```_ -  would result in _more_ memory being allocated?
Let's wait for  @FernandoBernardi  @EquineSolutions to give their opinions.

**Comment by MarcinZiabek** [comment]
@FernandoBernardi Thank you for testing. I highly appreciate your help. If possible, please share your findings. 😄

**Comment by FernandoBernardi** [comment]
After running in production for a week, I noticed:

- Memory consumption increased by 400MB over 5 days, starting at 140MB and reaching 541MB, averaging 80MB per day.
- The memory growth is slower than before, but I think there could be a bit more GC memory pressure.

If I call GC.Collect() after each PDF generation, it solves the issue, but of course, it's not ideal.

**Comment by 929496959** [comment]
We have the same exact problem

**Comment by leandrobattochio** [comment]
> We have the same exact problem

Can you update to latest version and share your findings please? We are trying to solve this problem.

**Comment by FernandoBernardi** [comment]
I had a huge improvement setting `QuestPDF.Settings.EnableCaching = false;`
Because it's enabled by default and is probably the root of all the memory leak problems;

My example:

```
public class ReportService : IReportService
 {
        public ReportService()
        {
            QuestPDF.Settings.License = LicenseType.Community;
            QuestPDF.Settings.EnableCaching = false;
        }
        
        public ValueTask<byte[]> GenerateMyLayout(MyLayoutParams myLayoutParams)
        {
            var document = new MyLayout(myLayoutParams).Compose().GeneratePdf();
            return ValueTask.FromResult(document);
        }
}
```

It seems to have fixed it for me.

**Comment by 929496959** [comment]
> > We have the same exact problem我们有同样的问题
> 
> Can you update to the latest version and share your findings please? We are trying to solve this problem.您能更新到最新版本并分享您的发现吗？我们正在尝试解决这个问题。

I used a small amount of larger images in the project, which caused a surge in memory
我是在项目中少量使用了比较大的图片导致内存暴涨

The usage method is as follows
使用方式如下
`
//The code is in a loop
//代码处在循环中
RelativeItem().PaddingTop(0).MaxHeight(330).Image(pngpath, ImageScaling.FitArea);
`

**Comment by MarcinZiabek** [comment]
@929496959 I am glad that some improvement has already been made. Could you please try the latest 2025.1.6 release?

**Comment by 929496959** [comment]
> [@929496959](https://github.com/929496959) I am glad that some improvement has already been made. Could you please try the latest 2025.1.6 release?

The updated version 2025.1.6 currently has a memory usage of 165MB based on my test cases
 更新的版本2025.1.6 根据我的测试用例目前情况内存占用是165M

**Comment by FernandoBernardi** [comment]
@MarcinZiabek I tested with the version 2025.1.6 in production but it still the same, it grows 100mb per day in my case.

**Comment by 929496959** [comment]
> [@MarcinZiabek](https://github.com/MarcinZiabek) I tested with the version 2025.1.6 in production but it still the same, it grows 100mb per day in my case.

My usage method is to end the process after it runs, not to have the process permanently reside
我的使用方式是运行完就结束进程,不是进程常驻

**Comment by MarcinZiabek** [comment]
@FernandoBernardi Thank you so much for testing the latest version—I truly appreciate your help!

Could you please answer the following questions?
1) How many PDF documents do you generate per day? Dozens, hundreds, or thousands?
2) What is the typical complexity of each document? For example: a single page with text, multiple pages with text and images, or hundreds of pages with complex graphics?
3) Do you encounter any failures during PDF generation? If so, how many per day (an estimate is fine)?
4) Do you think the increased memory usage could be due to improperly released memory when generation fails?
5) Are you confident in your previous observation that high memory usage is strongly linked to the Settings.EnableCaching mechanism? I’m curious if others have noticed a similar correlation.
6) Does your code include a structure similar to this?

    ```c#
    someContainer.Image(Image.FromFile(someFilePath));
    // or
    someContainer.Image(Image.FromStream(someStream));
    // or
    someContainer.Image(Image.FromBinaryData(someByteArray));
    ```
    
    Specifically, do you create an Image object first and then pass it to someContainer.Image() in a single place, rather than directly providing the file path, stream, or byte array?

**Comment by FernandoBernardi** [comment]
@MarcinZiabek 
1 - 2,000 PDFs daily.

2 - The PDFs contain multiple pages with images, text, and tables, but no complex graphics.

3 - No failures currently. However, I previously had issues with fixed heights in some places. That was my fault, but I fixed it.

4 - I don't think so, cuz there is no failure logs related to PDF generation in my Docker container and no customer complained.

5 - No, at first it seems to work fine and uses less memory, but I’ve noticed it still grows slowly over time.

6 - I only use byte arrays, the image comes from api request and is not loaded locally, but in some documents I use ZXing to generate QRCode.

**Comment by MarcinZiabek** [comment]
@FernandoBernardi @leandrobattochio @EquineSolutions @JanHergenhan @kerams @sps-campbellwray @JeremyVm @AntoineGLogaia @troncomputers 

First of all, I would like to sincerely thank you all for your help in identifying and resolving memory leak issues in QuestPDF. I truly appreciate your involvement, professionalism, and patience. The insights you’ve shared have been incredibly helpful and continue to guide improvements in the library with each new release.

Over the past two months, I’ve focused primarily on enhancing memory management and optimizing resource usage. Last Friday, I released version 2025.1.7, which I believe addresses the memory leak issue some of you encountered. While the leak was relatively minor, it could have accumulated over time when generating a large number of long documents.

If you get a chance, please consider updating to the latest version and letting me know if the issue persists.

As always, I remain fully committed to resolving quality-related issues, including memory leaks, and ensuring the best experience for all users.

**Comment by FernandoBernardi** [comment]
Thank you @MarcinZiabek, you are awesome!

It's been running in production for 2 days and the container is still at 290MB of RAM, which is excellent.

**Comment by MarcinZiabek** [comment]
I'm happy to hear that - thank you for testing 😄 

Before we proceed with closing this issue, let’s wait for confirmation after long-term use, as well as feedback from other developers. Fingers crossed!

**Comment by MarcinZiabek** [comment]
@FernandoBernardi Over a week has passed since you confirmed that the memory leak issue had been resolved. Could you please confirm whether memory usage is still behaving as expected so I can close this issue?

**Comment by scott-parkhill** [comment]
Yes please confirm @FernandoBernardi I'd really like to know this as someone bringing QuestPDF into our production environment.

**Comment by AntoineGLogaia** [comment]
Memory leaks seems resolved in our production environnement. GG @MarcinZiabek

**Comment by FernandoBernardi** [comment]
@scott-parkhill 
@MarcinZiabek 

Yes, it has been running in production over a month and memory still between 200~400mb in release 2025.1.7;

For me it's fixed.

**Comment by sps-campbellwray** [comment]
@FernandoBernardi @AntoineGLogaia 

Are you running in containers (Docker) or on ARM hardware? I am still having issues and I'm not really sure what to try next...

<img width="1400" alt="Image" src="https://github.com/user-attachments/assets/709069f4-1d21-47f2-b7d5-7f8036eb759c" />

**Comment by AntoineGLogaia** [comment]
@sps-campbellwray 

i'm running on docker linux on x64 arch

**Comment by MarcinZiabek** [comment]
In Q1 2025, a significant effort was made to address memory leak issues and optimise memory consumption. Since Q2 2025, we have not received any reports related to memory leak problems, so we are closing this issue. :confirm 

I would like to thank everybody involved in the investigation and testing - your help in making QuestPDF stable and reliable has been invaluable! ❤️
