### ISSUE TITLE
Keep spaces or tabs in Text element

### ISSUE THREAD

**Issue by MichelMichels** [QuestPDF/QuestPDF#125]
**Describe the bug**
It seems that whitespace in the Text element is omitted when writing to a PDF. Tabs also don't seem supported. Am I doing something wrong/

**To Reproduce**
https://github.com/MichelMichels/questpdf-line-bug/tree/text-spacing 

**Expected behavior**
I'd expect the spaces to be present in the rendered PDF.

**Screenshots**
![image](https://user-images.githubusercontent.com/6505319/154662467-9559c0d5-244e-4ade-9395-fd9b5ef8d509.png)

**Comment by MarcinZiabek** [comment]
This is behavior has two reasons:
1) Spaces at the beginning and end of line are removed by QuestPDF - this is to make it similar to HTML and reduce corner cases when wrapping text to next lines. I am considering changing this behavior in one of the future realases, so to make spaces visible and show the real/original value.
2) Tabs are not supported most likely due to limitations in SkiaSharp text rendering method. I think this can be fixed by introducing text shaping functionality that is already planned (and needed to support more complex languages, e.g. Arabic).

**Comment by MichelMichels** [comment]
No problem! I'll look forward to future releases.

**Comment by MichelMichels** [comment]
I'm trying to add page numbers and now I'm also getting the disappearing spaces. I find this confusing as the documentation has an example with spaces included at https://www.questpdf.com/documentation/getting-started.html#header-implementation

```csharp
column.Item().AlignRight().Text(text =>
  {
      text.DefaultTextStyle(Typography.Small);

      text.Span("page ");
      text.CurrentPageNumber();
      text.Span(" of ");
      text.TotalPages();
  });
```

**Comment by MarcinZiabek** [comment]
@MichelMichels I am very sorry of this problem. The observed behavior is not associated to the topic of this issue. It is just a bug introduced in the 2022.2.6 release. This should be fixed within the 2022.2.7 version. Please give it a try 😁

**Comment by MichelMichels** [comment]
This is indeed fixed in the version mentioned!

**Comment by wbittlehsl** [comment]
@MarcinZiabek I hate to resurrect an old issue, but are tabs still not supported?  I'm using 2022.8.2 and I'm seeing non-printables (squares) instead of the tabs similar to the above.
