### ISSUE TITLE
Previewer 2022.9.0 uses SkiaSharp 2.88.2

### ISSUE THREAD

**Issue by jnyrup** [QuestPDF/QuestPDF#343]
**Describe the bug**
I just upgraded to newest QuestPDF and QuestPDF.Previewer and experienced the same symptoms as described in #315.
When opening the QuestPDF.Previewer nuget package I see it includes SkiaSharp 2.88.2 whereas QuestPDF itself references 2.80.4.

**To Reproduce**

**Expected behavior**
QuestPDF and QuestPDF.Previewer should reference the same version of SkiaSharp.

**Screenshots**

**Additional context**

**Comment by MarcinZiabek** [comment]
This is something that confuses me for a couple of hours already. In csproj, I have specifically configured version 2.80.4. Avalonia-related dependencies should not upgrade the SkiaSharp version, via transitive dependency. When extracting nupkg file, I clearly see SkiaSharp 2.80. But when opening with DotPeek, there is 2.88 reference. To make the matter even more confusing, when I build in Debug mode, everything is correct, only Release mode is not functioning.

**Comment by jnyrup** [comment]
Do you build the published nugets locally?
I'd recommend using e.g. Github Actions (or any other build agent) to avoid e.g. locally defined nuget feeds to interfere.

**Comment by MarcinZiabek** [comment]
As a last resort, I decided to clear all local nuget package caches. And guess what, it has just worked! Haven't seen this type of issue for at least 3 years... Too bad I was fighting with this problem till 4 a.m.

Anyway, thank you for finding this version mismatch. You gave me that extra push to recheck/compare versions.

**Comment by MarcinZiabek** [comment]
Now, we need to wait for Nuget to process the new version. They often list new realease and still taking an hour or so to scan it. I guess it is because of the previewer nuget file size.

**Comment by jnyrup** [comment]
Feel free to copy from FluentAssertions, we use [NUKE](https://nuke.build/) by Matthias Koch which makes build pipelines _much_ less painful to work with.

https://github.com/fluentassertions/fluentassertions/blob/develop/.github/workflows/build.yml
https://github.com/fluentassertions/fluentassertions/tree/develop/Build

**Comment by MarcinZiabek** [comment]
Thank you! I will certainly investigate your approach!

**Comment by jnyrup** [comment]
Since the original purpose of this issue is solved, I'm closing it.

**Comment by cesh13** [comment]
Seems like this is still an issue for previewer 2022.11.0, this is the version that comes with the QuestPDF.Previewer
<img width="451" alt="image" src="https://user-images.githubusercontent.com/20121829/200881886-12d0a991-95c3-4783-ba70-b475e3d67c55.png">

And this is the one that comes with QuestPDF 2022.11.0
![image](https://user-images.githubusercontent.com/20121829/200882220-19a7bacf-b76c-4b69-8d00-b2a81edc8511.png)

Am I still missing something, since I also get the issue described in https://github.com/QuestPDF/QuestPDF/issues/315

**Comment by MarcinZiabek** [comment]
Ok then, I really need to invest in the automated build in GitHub! 😁 
I will do my best to fix the Previewer version tomorrow. Thank you for noticing this issue.

**Comment by MarcinZiabek** [comment]
Fixed 😁

**Comment by cesh13** [comment]
Just tested, working great now, thanks a lot @MarcinZiabek 👏
