### ISSUE TITLE
Table that repeats on another page when using ShowEntire on a following second table

### ISSUE THREAD

**Issue by tr4cks** [QuestPDF/QuestPDF#438]
**Describe the bug**
I created 2 tables that follow each other in the same page. I wanted the second table to be always fully visible so I applied the `ShowEntire` option to it. However, when the second table should be automatically moved to the second page when the first one is too big (at a specific location) then the first table is also duplicated on the second page.

**To Reproduce**
I tried to reduce the code as much as possible to understand the problem (it was not obvious). You can find it at the following address as well as the generated pdf -> https://github.com/tr4cks/bug-questpdf
The place where `ShowEntire` is used -> https://github.com/tr4cks/bug-questpdf/blob/main/InvoiceDocument.cs#L56

**Expected behavior**
The first table should not be repeated on the second page.

**Screenshots**
You can find the generated pdf in the repository.

**Additional context**
I am under mac m1. Don't know if this is important or not.

**Comment by tr4cks** [comment]
I had not put a header on the second table, I saw that it was necessary to put it apparently in the documentation but after having tested it does not change anything.
However, separating the 2 tables with another block allows to temporarily fix the problem.
This block can't be of size 0 otherwise it doesn't work.

```csharp
column.Item().Height(0.5f);
```

**Comment by MarcinZiabek** [comment]
Thank you for sharing this issue. I will investigate this problem within next couple of days 😁

**Comment by MarcinZiabek** [comment]
This issue will be fixed soon as part of the 2022.12.1 release.

**Comment by MarcinZiabek** [comment]
This is fixed in the 2022.12.1 release. Please test 😁

**Comment by tr4cks** [comment]
Maybe I'm wrong but I tried my [example]( https://github.com/tr4cks/bug-questpdf) by upgrading the library to 2022.12.1 version and I still have the same problem.

**Comment by MarcinZiabek** [comment]
That's interesting. I have tested the new release with your code, yet with a couple of changes. Would y

Mainly I replaced code of type:

```csharp
.PaddingHorizontal(2, Unit.Centimetre)
.Column(column => column.Item().Element(ComposeContent));
```

with:

```csharp
.PaddingHorizontal(2, Unit.Centimetre)
.Element(ComposeContent);
```

Right now, the layout engine uses floating point based arithmetic that may cause this type of issues. Even though your code is technically correct, you may experience rounding errors. I am planning to update the library implementation using integer based arithmetic in one of the future releases. Essentially removing a whole family of issues of this kind 😁

**Comment by MarcinZiabek** [comment]
Since there has been no recent activity, I’m closing this issue. If you have a similar request in the future, please feel free to open a new GitHub issue. Thanks for your feedback! ❤️
