### ISSUE TITLE
Unexpected spacing when drawing text in table cells

### ISSUE THREAD

**Issue by kl1mm** [QuestPDF/QuestPDF#949]
Hey together,

we are trying to render multi-line, formatted text in a table cell.
To do this, we use the "Text(Action&lt;TextDescriptor&gt; td)" method from QuestPdf.
Unfortunately, in comparison to the simple call of "Text(string text)", this leads to inexplicable free spaces around the text.

![image](https://github.com/QuestPDF/QuestPDF/assets/18304813/9392af3f-d3fe-4f7f-b03f-23d8b5456d99)

**To Reproduce**
Here is the littel snippet i used to prepare the screenshot
```csharp
    table.Header(HeaderCells());
    table.ColumnsDefinition(cd =>
    {
        cd.ConstantColumn(100);
        cd.ConstantColumn(200);
    });

    // Using Text(string text)
    table.Cell().Column(1).Row(1).Element(CellStyle).Text("Normal Text");
    table.Cell().Column(2).Row(1).Element(CellStyle).Text("Hello123");

    // Using Text(Action<TextDescriptor> td)
    // !!! Here we got unexpected spacings !!!
    table.Cell().Column(1).Row(2).Element(CellStyle).Text(td =>
    {
        td.Element().DebugArea().Width(80).Text("Text with Elemnt and Width");
    });
    table.Cell().Column(2).Row(2).Element(CellStyle).Text("Hello123");

    // Using Text(Action<TextDescriptor> td)
    // !!! By drawing a Span before the spacing issue is gone !!!
    table.Cell().Column(1).Row(3).Element(CellStyle).Text(td =>
    {
        td.Span("_");
        td.Element().DebugArea().Width(80).Text("Fixed with Span before");
    });
    table.Cell().Column(2).Row(3).Element(CellStyle).Text("Hello123");

    IContainer CellStyle(IContainer c) => DefaultCellStyle(c).Element(e => e.DefaultTextStyle(textStyle));
```

**Expected behavior**
No extra space when using the "Text(Action&lt;TextDescriptor&gt; td)" with some extra stylings/Elements that not affact Bounds

best regards

**Comment by MarcinZiabek** [comment]
Great catch! 😄 

It is a relatively uncommon use case. This bug should be fixed in the `2024.7.0` version. Could you please give it a try?

**Comment by kl1mm** [comment]
Hey @MarcinZiabek,
its much better with `2024.7.0` but still not correct i think:

![image](https://github.com/user-attachments/assets/8e855b48-e627-445b-b115-2dbaf28043a4)

```csharp
  table.Header(HeaderCells());
  table.ColumnsDefinition(cd =>
  {
      cd.ConstantColumn(200);
      cd.RelativeColumn(100);
  });

  // Using Text(string text)
  table.Cell().Column(1).Row(1).Element(CellStyle).Text("Normal Text");
  table.Cell().Column(2).Row(1).Element(CellStyle).Text("Hello123");

  // Using Text(Action<TextDescriptor> td)
  // !!! By drawing a Span before the spacing issue is gone !!!
  table.Cell().Column(1).Row(3).Element(CellStyle).Text(td =>
  {
      td.Span("test");
      td.Element().Width(150).Text("Why i am not aligned with 'td.Span(\"test\");'");
  });
  table.Cell().Column(2).Row(3).Element(CellStyle).Text("Hello123");

  IContainer CellStyle(IContainer c) => DefaultCellStyle(c).Element(e => e.DefaultTextStyle(textStyle));
```

best regards

**Comment by MarcinZiabek** [comment]
Thank you for checking. This behavior is expected. The `text.Element()` method is used for injecting custom content into the text, e.g., images. The layout algorithm cannot access the text baseline of injected content. 

What thing are you trying to accomplish? I am positive there are other approaches already available.

**Comment by kl1mm** [comment]
Hey @MarcinZiabek ,
I have a text with \r\n (line breaks) and \t (tabs). I tried to display the tabs with this variant.

```csharp
  const string myText = "This is a sample.\r\n Second line:\t Value\r\nThird line:\t Value2";
  table.Cell().Column(1).Element(CellStyle).Text(td =>
  {
      foreach(string line in myText.Split("\r\n"))        
          if(line.Contains('\t'))
          {
              string[] tabs = line.Split("\t");
              foreach(string tab in tabs)
                  td.Element().MinWidth(40).Text(tab);
              td.EmptyLine();
          }
          else
              td.Line(line);
  });
```
But for me the yellow area/free space is wrong
![image](https://github.com/user-attachments/assets/2931094d-d599-4638-a592-4ac01074ecb8)

best regards

**Comment by MarcinZiabek** [comment]
My suggestion is to first parse your text into (key, value) pairs and then display the content using layout structures such as tables.

**Comment by kl1mm** [comment]
Yes, you're probably right, Table in Table :)
That's how it works in my case.

Thanks for the advice
