### ISSUE TITLE
Companion app crashes when click open in code editor

### ISSUE THREAD

**Issue by Erikvdv** [QuestPDF/QuestPDF#989]
Using Macbook pro M1 with Rider.
When I select a segment and click open in code editor the companion app crashes and is closed immediately

**Comment by MarcinZiabek** [comment]
Could you please elaborate a bit more about opening the code? Have you changed the default editor in the settings?

The Companion App `2024.10.2` should now display an error message if the code opening function fails. I expect at least this improvement in your case in place of an app crash. 

It would be great to learn your operating system, editor, etc.

**Comment by MarcinZiabek** [comment]
The QuestPDF Companion source code is yet to be open-sourced in the upcoming feature. Till then, I would like to ensure its quality and stability 😄

Could you please test the 2024.10.3 release? It should fix the issue of the application crashing when the target editor is not available.

**Comment by Erikvdv** [comment]
Indeed, it is not crashing anymore and I get a red error bottom sheet with Cannot open the source code in Rider, please check your settings

**Comment by Erikvdv** [comment]
I checked with the latest release. Rider was not added to my path. I did add it and can open rider from the terminal now. Unfortunately it is still not working from the companion app

**Comment by MarcinZiabek** [comment]
The following command is executed. 

```sh
rider --line $lineNumber $absoluteFilePath
```

Do you think that there is any security or access-related problem? It may work on my end, as the application is built on my Mac. If the app comes from an external provider, the issue could appear.

I am planning to purchase a code signing certificate. I hope it will streamline the installation process and fix any security-related problems.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
